config/routes.rb
Rails.application.routes.draw do

#          new_user_session GET      /users/saml/sign_in(.:format)                       devise/saml_sessions#new
#              user_session POST     /users/saml/auth(.:format)                          devise/saml_sessions#create
#      destroy_user_session DELETE   /users/sign_out(.:format)                           devise/saml_sessions#destroy
#     metadata_user_session GET      /users/saml/metadata(.:format)                      devise/saml_sessions#metadata
# idp_sign_out_user_session GET|POST /users/saml/idp_sign_out(.:format)                  devise/saml_sessions#idp_sign_out


  devise_for :users, controllers: {
    saml_sessions: 'users/saml_sessions'
  }

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

    resources :uke_regulations, only: [:index]

    resources :works, only: [:index] do
      post 'datatables_index', on: :collection # for User
      post 'datatables_index_trackable', on: :collection # for Trackable
      post 'datatables_index_user', on: :collection # for User
    end

    resources :users do
      get 'select2_index', on: :collection
      post 'datatables_index', on: :collection
      get 'datatables_index_role', on: :collection # Displays users for showed role
      get 'datatables_index_group', on: :collection # Displays users for showed group
      resources :attachments, module: :users, only: [:create] do
        post 'create_folder', on: :collection
      end
    end

    resources :roles do
      post 'datatables_index', on: :collection
      get 'datatables_index_user', on: :collection # Displays roles for showed user
      resources :users, only: [:create, :destroy], controller: 'roles/users'
    end    

    resources :groups do
      get 'select2_index', on: :collection
      post 'datatables_index', on: :collection
      get 'datatables_index_user', on: :collection # Displays groups for showed user
      resources :users, only: [:create, :destroy], controller: 'groups/users'
    end    

    resources :archives do
      post 'datatables_index', on: :collection
      get 'datatables_index_group', on: :collection # Displays archives for showed group
      get 'datatables_index_user', on: :collection # Displays archives for showed user
      get 'help_new_edit', on: :collection
      post 'send_link_to_archive_show', on: :member
      resources :components, module: :archives, only: [:create] do
        post 'create_folder', on: :collection
      end
    end

    resources :components, except: [:create] do 
      get 'datatables_index', on: :collection # for Trackable
      get 'zip_and_download', on: :collection
      patch 'move_to_parent', on: :collection
      get 'download', on: :member
      get 'download_simple', on: :member
      post 'send_link_to_component_download', on: :member
      post 'send_link_to_component_download_simple', on: :member
    end

    get 'datatables/lang'
    get 'static_pages/home'
    get 'static_pages/declaration'

    root to: 'static_pages#home'
	end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  # get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302),
  #               constraints: { path: /(?!(#{I18n.available_locales.join("|")})\/).*/ },
  #               format: false


  namespace :api, defaults: { format: :json } do
    require 'api_constraints'
    namespace :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      get :token, controller: 'base_api'

    end

    namespace :v2 do
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  include ActionView::Helpers::TextHelper

  delegate :url_helpers, to: 'Rails.application.routes'


  # relations
  has_many :members, dependent: :destroy
  has_many :users, through: :members

  has_many :archivizations, dependent: :destroy
  has_many :accesses_archives, through: :archivizations, source: :archive

  belongs_to :author, class_name: "User"
  has_many :works, as: :trackable

  # validates
  validates :name, presence: true,
                    length: { in: 1..100 },
                    uniqueness: { case_sensitive: false }

  validates :note, length: { in: 0..500 }

  # callbacks

 
  # additionals
  # accepts_nested_attributes_for :members, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :members, allow_destroy: true, :reject_if => proc { |attributes| attributes['user_id'].blank? }

  def log_work(action = '', action_user_id = nil)
    worker_id = action_user_id || self.author_id
    url = "<a href=#{url_helpers.group_path(self.id, locale: :pl)}>#{self.fullname}</a>".html_safe

    Work.create!(trackable_type: 'Group', trackable_id: self.id, action: "#{action}", author_id: worker_id, url: "#{url}", 
      parameters: self.to_json(except: [:author_id], include: { author: {only: [:id, :user_name, :email]}, 
                                                                members: {only: [:id, :created_at], 
                                                                  include: {user: {only: [:id, :user_name, :email]}, 
                                                                            group: {only: [:id, :name]},
                                                                            author: {only: [:id, :user_name, :email]} }
                                                                  } }))
  end

  def fullname
    "#{name}"
  end

  def fullname_was
    "#{name_was}"
  end

  def note_truncate
    truncate(Loofah.fragment(self.note).text, length: 100)
  end


  # Scope for select2: "group_select"
  # * parameters   :
  #   * +query_str+ -> string for search. 
  #   Eg.: "Jan ski@"
  # * result   :
  #   * +scope+ -> collection 
  #
  scope :finder_group, ->(q) { where( create_sql_string("#{q}") ) }

  # Method create SQL query string for finder select2: "group_select"
  # * parameters   :
  #   * +query_str+ -> string for search. 
  #   Eg.: "Jan ski@"
  # * result   :
  #   * +sql_string+ -> string for SQL WHERE... 
  #   Eg.: "((groups.name ilike '%Jan%' OR groups.email ilike '%Jan%') AND (groups.name ilike '%ski@%' OR groups.email ilike '%ski@%'))"
  #
  def self.create_sql_string(query_str)
    query_str.split.map { |par| one_param_sql(par) }.join(" AND ")
  end

  # Method for glue parameters in create_sql_string
  # * parameters   :
  #   * +one_query_word+ -> word for search. 
  #   Eg.: "Jan"
  # * result   :
  #   * +sql_string+ -> SQL string query for one word 
  #   Eg.: "(groups.name ilike '%Jan%' OR groups.email ilike '%Jan%')"
  #
  def self.one_param_sql(one_query_word)
    #escaped_query_str = sanitize("%#{query_str}%")
    escaped_query_str = Loofah.fragment("'%#{one_query_word}%'").text
    "(" + %w(groups.name).map { |column| "#{column} ilike #{escaped_query_str}" }.join(" OR ") + ")"
  end

  private
  

end

app/controllers/groups/users_controller.rb
class Groups::UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def create
    group = Group.find(params[:group_id])
    user = User.find(params[:id])

    authorize group, :add_remove_group_user? 

    member = Member.create!(group: group, user: user, author: current_user)
    member.log_work_for_user('add_group_to_user', current_user.id)
    member.log_work_for_group('add_user_to_group', current_user.id)

    head :ok
  end

  def destroy
    group = Group.find(params[:group_id])
    user = User.find(params[:id])

    authorize group, :add_remove_group_user? 

    if group.present? && user.present?
      member = Member.find_by(group: group, user: user)
      destroyed_clone = member.clone
      if member.destroy
        destroyed_clone.log_work_for_user('remove_group_from_user', current_user.id)
        destroyed_clone.log_work_for_group('remove_user_from_group', current_user.id)
      end
    end

    head :no_content
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized, except: [:index, :datatables_index, :datatables_index_user]
  before_action :set_group, only: [:show, :edit, :update, :destroy]


  def datatables_index_user
    checked_filter = (params[:checked_only_filter].blank? || params[:checked_only_filter] == 'false' ) ? nil : true
    respond_to do |format|
      format.json { render json: UserGroupsDatatable.new(params, view_context: view_context, only_for_current_user_id: params[:user_id], checked_only_filter: checked_filter) }
    end
  end

  def datatables_index
    respond_to do |format|
      format.json { render json: GroupDatatable.new(params, view_context: view_context) }
    end
  end

  def select2_index
    authorize :group, :index?
    params[:q] = params[:q]
    @groups = Group.order(:name).finder_group(params[:q])
    @groups_on_page = @groups.page(params[:page]).per(params[:page_limit])
    
    render json: { 
      groups: @groups_on_page.as_json(methods: :fullname, only: [:id, :fullname]),
      meta: { total_count: @groups.count }  
    } 
  end

  # GET /groups
  # GET /groups.json
  def index
    authorize :group, :index?
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @for_archive = Archive.find(params[:archive_id]) if params[:archive_id].present? 
    authorize @group, :show?
  end

  # GET /groups/new
  def new
    @group = Group.new
    @group.name = params[:group][:name].strip if params.dig(:group, :name).present? 
    @group.author = current_user
    authorize @group, :new?
  end

  # GET /groups/1/edit
  def edit
    authorize @group, :edit?
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    authorize @group, :create?
    respond_to do |format|
      if @group.save
        @group.log_work('create', current_user.id)
        format.html { 
          flash[:success] = t('activerecord.successfull.messages.created', data: @group.fullname)
          redirect_to @group 
        }
        format.json { render :show, status: :created, location: @group }
        format.js { render :create }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    authorize @group, :update?
    respond_to do |format|
      # if @group.update(name: params[:group][:name], note: params[:group][:note], special: params[:group][:special],activities: params[:group][:activities].split)
      if @group.update(group_params)
        @group.log_work('update', current_user.id)
        format.html { 
          flash[:success] = t('activerecord.successfull.messages.updated', data: @group.fullname)
          redirect_to @group 
        }
        format.json { render :show, status: :ok, location: @group }
        format.js { render :update }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    authorize @group, :destroy?
    destroyed_clone = @group.clone
    if @group.destroy
      destroyed_clone.log_work('destroy', current_user.id)
      flash[:success] = t('activerecord.successfull.messages.destroyed', data: @group.fullname)
      redirect_to groups_url
    else 
      flash.now[:error] = t('activerecord.errors.messages.destroyed', data: @group.fullname)
      #redirect_to :back
      render :show
    end      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      defaults = { author_id: "#{current_user.id}" }
      params.require(:group).permit(:name, :note, :author_id, members_attributes: [:id, :user_id, :author_id, :_destroy]).reverse_merge(defaults)
    end

end

app/helpers/groups_helper.rb
module GroupsHelper

  ICON = "user-friends"

  def group_icon_legend
    fa_icon(ICON)
  end

  def group_legend
    fa_icon(ICON, text: t("groups.show.title"))
  end

  def group_show_legend
    fa_icon(ICON, text: t("groups.show.title"))
  end

  def group_index_legend
    fa_icon(ICON, text: t("groups.index.title"))
  end

  def group_edit_legend(data_obj=nil)
    data_obj.present? ? fa_icon(ICON, text: t("groups.edit.title") + ": " + data_obj.fullname_was) : fa_icon(ICON, text: t("helpers.links.edit") )
  end

  def group_new_legend(data_obj=nil)
    data_obj.present? ? fa_icon(ICON, text: t("groups.new.title") + ": " + data_obj.fullname) : fa_icon(ICON, text: t("helpers.links.new") )
  end

  def group_new_edit_legend(data_obj)
    data_obj.new_record? ? group_new_legend(data_obj) :  group_edit_legend(data_obj)
  end

  def group_info_legend(data_obj)
    group_show_legend + ": " + data_obj.fullname
  end

end

app/views/groups/_archives.html.erb
<div id="tab_archives">
  <fieldset class="my-fieldset">
    <legend class="my-fieldset colored-title"><%= subtitle %>&nbsp;&nbsp;-&nbsp;&nbsp;<%= archive_index_legend %></legend>

    <div class="row">
      <div class="col-sm-12">
        <table id="group-archives-table" class="hover cell-border compact" width="100%" 
          data-source="<%= datatables_index_group_archives_path(group_id: @group.id, format: :json) %>"
          data-locale_url="<%= datatables_lang_path(format: :json) %>">
          <thead>
            <tr>
              <th>ID</th>
              <th><%= Archive.human_attribute_name(:name) %></th>
              <th><%= Archive.human_attribute_name(:expiry_on) %></th>
              <th><%= Archive.human_attribute_name(:note) %></th>
              <th><%= t('table_group_archivization') %></th>
            </tr>
          </thead>
          <tbody>
             <!--data from JSON -->
          </tbody>
        </table>
      </div> <!--/col-sm-12 -->
    </div> <!--/row -->

  </fieldset>
</div>

app/views/groups/_data.html.erb
<div id="tab_data">
  <fieldset class="my-fieldset">
    <legend class="my-fieldset colored-title"><%= subtitle %></legend>
    <div class="row">

      <div class="col-sm-12">

        <%= form_errors_for @group %>

        <div class="row">
          <div class="col-sm-6">
            <div class="row">

              <div class="form-group col-sm-12">
                <p><strong><%= Group.human_attribute_name(:name) %></strong></p>
                <%= @group.name %>
              </div>

            </div>  <!-- /row -->
          </div>  <!-- /col-sm-6 -->

          <div class="col-sm-6">
            <div class="row">
              <div class="form-group col-sm-12">
                <% if @group.note.html_safe.size > 0 %>
                  <blockquote>
                    <%= @group.note.html_safe %>
                  </blockquote>
                <% end %>
              </div>
            </div>
          </div> <!--/col-sm-6 -->
        </div>  <!-- /row -->

        <hr class="hr-without-top-margin">

        <div class="row">
          <div class="col-sm-12">

            <% if policy(@group).destroy? %>
              <%= link_to group_path(@group),
                                  method: :delete,
                                  data: { confirm: t('helpers.links.confirm_destroy', data: @group.name) }, 
                                  class: "btn btn-danger" do %>
                <span class="fa fa-trash"></span>
                <%= t("helpers.links.destroy") %>
              <% end %>
            <% end %>

            <% if policy(@group).edit? %>
              <%= link_to edit_group_path(@group), class: "btn btn-primary" do %>
                <span class="fa fa-edit"></span>
                <%= t("helpers.links.edit") %>
              <% end %>
            <% end %>

            <h6 class="pull-right"><%= last_updated_legend(@group) %></h6>

          </div> <!--/col-sm-12 -->
        </div> <!-- /row -->

      </div> <!--/col-sm-12-->  

    </div>
  </fieldset>
</div>

app/views/groups/_data_js.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h4 id="myModalLabel"><strong><%= group_info_legend(@group) %></strong></h4>
</div>
<div class="modal-body">

  <div class="row">

    <div class="col-sm-12">
<!--       <%= @group.note.html_safe %>
 -->
      <% if @group.note.html_safe.size > 0 %>
        <blockquote>
          <%= @group.note.html_safe %>
        </blockquote>
      <% end %>
    </div> <!--/col-sm-6 -->

    <div class="form-group col-sm-12">

<!-- 
class="<%#= @license.status == 'S' ? 'text-danger' : 'text-success' %>"

 -->      
      <% unless @for_archive.present? %>
        <% access_to_send_link = false %>
      <% else %>
        <% access_to_send_link = policy(@for_archive).send_link_to_archive_show? %>
      <% end %>

      <table class="table table-hover">
        <thead>
          <tr>
            <th><%= User.human_attribute_name(:email) %></th>
            <th><%= User.human_attribute_name(:first_name) %></th>
            <th><%= User.human_attribute_name(:last_name) %></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @group.users.order(:email).each do |rec| %>
            <tr>
              <td class="col-sm-5"><%= rec.email %></td>
              <td class="col-sm-3"><%= rec.first_name %></td>
              <td class="col-sm-3"><%= rec.last_name %></td>
              <td class="col-sm-1">

                  <% if access_to_send_link %>
                    <%= link_to send_link_to_archive_show_archive_path(@for_archive.id, users_ids: [rec.id] ),
                                        method: :post,
                                        remote: true,
                                        data: { confirm: t('helpers.links.confirm_send_mail_for_archive', data: rec.fullname) }, 
                                        class: "btn btn-xs btn-info" do %>
                      <span><%= send_email_with_share_legend %></span>
                    <% end %>
                  <% end %>

              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>

    <div class="col-sm-12">
      <h6 class="pull-right"><%= last_updated_legend(@group) %></h6>
    </div> <!--/col-sm-6 -->

  </div>  <!-- /row -->


</div>
<div class="modal-footer">

  <% if @for_archive.present? %>
    <% if policy(@for_archive).send_link_to_archive_show? %>
      <%= link_to send_link_to_archive_show_archive_path(@for_archive.id, users_ids: @group.users.ids ),
                          method: :post,
                          remote: true,
                          data: { confirm: t('helpers.links.confirm_send_mail_for_archive', data: t('to_all')) }, 
                          class: "pull-left btn btn-info" do %>
        <span><%= send_email_with_share_to_all_legend %></span>
      <% end %>
    <% end %>
  <% end %>

  <% if policy(@group).edit? %>
    <%= link_to edit_group_path(@group), remote: true, class: "pull-left btn btn-primary" do %>
      <span class="fa fa-edit"></span>
      <%= t("helpers.links.edit") %>
    <% end %>
  <% end %>

  <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true"><%= t('helpers.links.close') %></button>
</div>

app/views/groups/_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <%= form_with(model: group, local: true) do |f| %>

      <% input_disabled ||= false  
         #if input_disabled is not passed to the partial it doesn't crash. 
         # We default it to false 
      %>

      <%= form_errors_for group %>

      <div class="row">
        <div class="col-sm-6">
          <div class="row">
            <div class="form-group required col-sm-12">
              <%= f.label :name, class: 'control-label' %>
              <%= f.text_field :name, autofocus: true, class: 'form-control input-sm', disabled: input_disabled %>
            </div>
          </div>  <!-- /row -->
        </div>  <!-- /col-sm-6 -->


        <div class="col-sm-6">
          <div class="row">
            <div class="form-group col-sm-12">
              <%= f.label :note, class: 'control-label' %>
              <%= f.trix_editor :note %>
            </div>
          </div> <!-- /row -->
        </div> <!--/col-sm-6 -->
      </div>  <!-- /row -->


      <hr class="hr-without-top-margin">

      <div class="row">
        <div class="col-sm-12">

          <%= link_to group.new_record? ? groups_path() : group_path(group), class: "btn btn-default" do %>
            <%= back_from_new_or_edit_legend %>
          <% end %>

          <%= f.submit nil, class: 'btn btn-success' %>

        </div> <!--/col-sm-12 -->
      </div> <!-- /row -->

      
    <% end %>

  </div> <!--/col-sm-12-->
</div>

app/views/groups/_sidebar_edit.html.erb
<button class="sideber-button fa fa-chevron-right" onclick="changeSidebar(this)" title="<%=t('sidebar')%>" rel='tooltip'></button>

<div class="sidebar-content-small container-fluid">
  <div class="center"><%= group_icon_legend %></div>
  <hr>

  <div class="row">
    <div class="col-sm-12">

      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">

        <li role="presentation" class="brand-nav"><%= link_to groups_path, title: t('.index'), rel: 'tooltip' do %>
          <span class="fa fa-list"></span>
          <% end %>
        </li>

      </ul>

    </div>
  </div>

</div>    


<div class="sidebar-content-large hidden container-fluid">
  <div class="center"><%= group_legend %></div>
  <hr>
  <div class="row">
    <div class="col-sm-12">


      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">
 
        <li role="presentation" class="brand-nav"><%= link_to groups_path, title: t('.index'), rel: 'tooltip' do %>
            <%= back_to_index_legend %>
          <% end %>
        </li>

      </ul>


    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-sm-12">
      <div class="center"><%= fa_icon("edit", size: '2x') %></div>
      <h3 class="center"><%= t('helpers.links.edit') %></h3>
    </div>
  </div>


</div>

app/views/groups/_sidebar_new.html.erb
<button class="sideber-button fa fa-chevron-right" onclick="changeSidebar(this)" title="<%=t('sidebar')%>" rel='tooltip'></button>

<div class="sidebar-content-small container-fluid">
  <div class="center"><%= group_icon_legend %></div>
  <hr>

  <div class="row">
    <div class="col-sm-12">

      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">

        <li role="presentation" class="brand-nav"><%= link_to groups_path, title: t('.index'), rel: 'tooltip' do %>
          <span class="fa fa-list"></span>
          <% end %>
        </li>

      </ul>

    </div>
  </div>

</div>    


<div class="sidebar-content-large hidden container-fluid">
  <div class="center"><%= group_legend %></div>
  <hr>
  <div class="row">
    <div class="col-sm-12">


      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">
 
        <li role="presentation" class="brand-nav"><%= link_to groups_path, title: t('.index'), rel: 'tooltip' do %>
            <%= back_to_index_legend %>
          <% end %>
        </li>

      </ul>


    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-sm-12">
      <div class="center"><%= fa_icon("plus", size: '2x') %></div>
      <h3 class="center"><%= t('helpers.links.new') %></h3>
    </div>
  </div>


</div>

app/views/groups/_sidebar_show.html.erb
<button class="sideber-button fa fa-chevron-right" onclick="changeSidebar(this)" title="<%=t('sidebar')%>" rel='tooltip'></button>

<div class="sidebar-content-small container-fluid">
  <div class="center"><%= group_icon_legend %></div>
  <hr>

  <div class="row">
    <div class="col-sm-12">

      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">

        <li role="presentation" class="brand-nav active" title="<%= t('helpers.links.show') %>" rel='tooltip'>
          <a href="#group_show" aria-controls="group_show" role="tab" data-toggle="tab"><%= group_icon_legend %></a>
        </li>

        <% if policy(:user).index? %>
          <li role="presentation" class="brand-nav" title="<%= t('users.index.title') %>" rel='tooltip'>
            <a href="#users" aria-controls="users" role="tab" data-toggle="tab"><%= user_icon_legend %></a>
          </li>
        <% end %>

        <% if policy(:archive).index? %>
          <li role="presentation" class="brand-nav" title="<%= t('archives.index.title') %>" rel='tooltip'>
            <a href="#archives" aria-controls="archives" role="tab" data-toggle="tab"><%= archive_icon_legend %></a>
          </li>
        <% end %>

        <% if policy(:group).work? %>
          <li role="presentation" class="brand-nav" title="<%= t('works.index.title') %>" rel='tooltip'>
            <a href="#works" aria-controls="works" role="tab" data-toggle="tab"><%= work_icon_legend %></a>
          </li>
        <% end %>

        <hr>
        <li role="presentation" class="brand-nav"><%= link_to groups_path, title: t('.index'), rel: 'tooltip' do %>
          <span class="fa fa-list"></span>
          <% end %>
        </li>

      </ul>

    </div>
  </div>

</div>    


<div class="sidebar-content-large hidden container-fluid">
  <div class="center"><%= group_legend %></div>
  <hr>
  <div class="row">
    <div class="col-sm-12">

      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">

        <li role="presentation" class="brand-nav active" title="<%= t('helpers.links.show') %>" rel='tooltip'>
          <a href="#group_show" aria-controls="group_show" role="tab" data-toggle="tab"><%= group_show_legend %></a>
        </li>

        <% if policy(:user).index? %>
          <li role="presentation" class="brand-nav brand-nav-level-1" title="<%= t('users.index.title') %>" rel='tooltip'>
            <a href="#users" aria-controls="users" role="tab" data-toggle="tab"><%= user_index_legend %></a>
          </li>
        <% end %>

        <% if policy(:archive).index? %>
          <li role="presentation" class="brand-nav brand-nav-level-1" title="<%= t('archives.index.title') %>" rel='tooltip'>
            <a href="#archives" aria-controls="archives" role="tab" data-toggle="tab"><%= archive_index_legend %></a>
          </li>
        <% end %>

        <% if policy(:group).work? %>
          <li role="presentation" class="brand-nav brand-nav-level-1" title="<%= t('works.index.title') %>" rel='tooltip'>
            <a href="#works" aria-controls="works" role="tab" data-toggle="tab"><%= work_index_legend %></a>
          </li>
        <% end %>  

        <hr>
        <li role="presentation" class="brand-nav"><%= link_to groups_path, title: t('.index'), rel: 'tooltip' do %>
            <%= back_to_index_legend %>
          <% end %>
        </li>

      </ul>

    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-sm-12">
      <div class="center"><%= fa_icon("eye", size: '2x') %></div>
      <h3 class="center"><%= t('helpers.links.show') %></h3>
    </div>
  </div>


</div>

app/views/groups/_users.html.erb
<div id="tab_users">
  <fieldset class="my-fieldset">
    <legend class="my-fieldset colored-title"><%= subtitle %>&nbsp;&nbsp;-&nbsp;&nbsp;<%= user_index_legend %></legend>

    <div class="row">
      <div class="col-sm-12">
        <table id="group-users-table" class="hover cell-border compact" width="100%" 
          data-source="<%= datatables_index_group_users_path(group_id: @group.id, format: :json) %>"
          data-locale_url="<%= datatables_lang_path(format: :json) %>">
          <thead>
            <tr>
              <th>ID</th>
              <th><%= User.human_attribute_name(:email) %></th>
              <th><%= User.human_attribute_name(:last_name) %></th>
              <th><%= User.human_attribute_name(:first_name) %></th>
              <th><%= User.human_attribute_name(:note) %></th>
              <th><%= t('table_group_member') %></th>
              <th><%= t('table_action') %></th>
            </tr>
          </thead>
          <tbody>
             <!--data from JSON -->
          </tbody>
        </table>
      </div> <!--/col-sm-12 -->
    </div> <!--/row -->

  </fieldset>
</div>

app/views/groups/create.js.erb
//toastr['info']("Upadate UUID");

$("#myModal").find(".modal-content").html('');
$('#myModal').modal('hide');
toastr['success']("<%= t('activerecord.successfull.messages.created', data: @group.fullname) %>");

app/views/groups/edit.html.erb
<div class="grid-container">

  <div class="sidebar">
    <%= render 'sidebar_edit' %>
  </div>

  <div class="main-content">
    <br>
    <div class="container-fluid"> 
      <div class="row">
        <div class="col-sm-12">
          <fieldset class="my-fieldset">
            <legend class="my-fieldset colored-title"><%= group_edit_legend(@group) %></legend>
            <%= render 'form', group: @group %>
          </fieldset>
        </div>

      </div>

    </div> <!--/container-fluid--> 
  </div> <!--/main-content--> 

</div> <!--/grid-containe--> 