config/routes.rb
Rails.application.routes.draw do

#          new_user_session GET      /users/saml/sign_in(.:format)                       devise/saml_sessions#new
#              user_session POST     /users/saml/auth(.:format)                          devise/saml_sessions#create
#      destroy_user_session DELETE   /users/sign_out(.:format)                           devise/saml_sessions#destroy
#     metadata_user_session GET      /users/saml/metadata(.:format)                      devise/saml_sessions#metadata
# idp_sign_out_user_session GET|POST /users/saml/idp_sign_out(.:format)                  devise/saml_sessions#idp_sign_out


  devise_for :users, controllers: {
    saml_sessions: 'users/saml_sessions'
  }

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

    resources :uke_regulations, only: [:index]

    resources :works, only: [:index] do
      post 'datatables_index', on: :collection # for User
      post 'datatables_index_trackable', on: :collection # for Trackable
      post 'datatables_index_user', on: :collection # for User
    end

    resources :users do
      get 'select2_index', on: :collection
      post 'datatables_index', on: :collection
      get 'datatables_index_role', on: :collection # Displays users for showed role
      get 'datatables_index_group', on: :collection # Displays users for showed group
      resources :attachments, module: :users, only: [:create] do
        post 'create_folder', on: :collection
      end
    end

    resources :roles do
      post 'datatables_index', on: :collection
      get 'datatables_index_user', on: :collection # Displays roles for showed user
      resources :users, only: [:create, :destroy], controller: 'roles/users'
    end    

    resources :groups do
      get 'select2_index', on: :collection
      post 'datatables_index', on: :collection
      get 'datatables_index_user', on: :collection # Displays groups for showed user
      resources :users, only: [:create, :destroy], controller: 'groups/users'
    end    

    resources :archives do
      post 'datatables_index', on: :collection
      get 'datatables_index_group', on: :collection # Displays archives for showed group
      get 'datatables_index_user', on: :collection # Displays archives for showed user
      get 'help_new_edit', on: :collection
      post 'send_link_to_archive_show', on: :member
      resources :components, module: :archives, only: [:create] do
        post 'create_folder', on: :collection
      end
    end

    resources :components, except: [:create] do 
      get 'datatables_index', on: :collection # for Trackable
      get 'zip_and_download', on: :collection
      patch 'move_to_parent', on: :collection
      get 'download', on: :member
      get 'download_simple', on: :member
      post 'send_link_to_component_download', on: :member
      post 'send_link_to_component_download_simple', on: :member
    end

    get 'datatables/lang'
    get 'static_pages/home'
    get 'static_pages/declaration'

    root to: 'static_pages#home'
	end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  # get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302),
  #               constraints: { path: /(?!(#{I18n.available_locales.join("|")})\/).*/ },
  #               format: false


  namespace :api, defaults: { format: :json } do
    require 'api_constraints'
    namespace :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      get :token, controller: 'base_api'

    end

    namespace :v2 do
    end
  end
end

app/controllers/groups/users_controller.rb
class Groups::UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def create
    group = Group.find(params[:group_id])
    user = User.find(params[:id])

    authorize group, :add_remove_group_user? 

    member = Member.create!(group: group, user: user, author: current_user)
    member.log_work_for_user('add_group_to_user', current_user.id)
    member.log_work_for_group('add_user_to_group', current_user.id)

    head :ok
  end

  def destroy
    group = Group.find(params[:group_id])
    user = User.find(params[:id])

    authorize group, :add_remove_group_user? 

    if group.present? && user.present?
      member = Member.find_by(group: group, user: user)
      destroyed_clone = member.clone
      if member.destroy
        destroyed_clone.log_work_for_user('remove_group_from_user', current_user.id)
        destroyed_clone.log_work_for_group('remove_user_from_group', current_user.id)
      end
    end

    head :no_content
  end

end

app/controllers/roles/users_controller.rb
class Roles::UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def create
    role = Role.find(params[:role_id])
    user = User.find(params[:id])

    authorize role, :add_remove_role_user? 

    approval = Approval.create!(role: role, user: user, author: current_user)
    approval.log_work_for_user('add_role_to_user', current_user.id)
    approval.log_work_for_role('add_user_to_role', current_user.id)

    head :ok
  end

  def destroy
    role = Role.find(params[:role_id])
    user = User.find(params[:id])

    authorize role, :add_remove_role_user? 

    if role.present? && user.present?
      approval = Approval.find_by(role: role, user: user)
      destroyed_clone = approval.clone
      if approval.destroy
        destroyed_clone.log_work_for_user('remove_role_from_user', current_user.id)
        destroyed_clone.log_work_for_role('remove_user_from_role', current_user.id)
      end
    end

    head :no_content
  end

end

app/controllers/users/saml_sessions_controller.rb
require "ruby-saml"

class Users::SamlSessionsController < Devise::SessionsController
  include DeviseSamlAuthenticatable::SamlConfig
  unloadable if Rails::VERSION::MAJOR < 4
  if Rails::VERSION::MAJOR < 5
    skip_before_filter :verify_authenticity_token
    prepend_before_filter :verify_signed_out_user, :store_info_for_sp_initiated_logout, only: :destroy
  else
    skip_before_action :verify_authenticity_token, raise: false
    prepend_before_action :verify_signed_out_user, :store_info_for_sp_initiated_logout, only: :destroy
  end

  def new
    idp_entity_id = get_idp_entity_id(params)
    request = OneLogin::RubySaml::Authrequest.new
    auth_params = { RelayState: relay_state } if relay_state
    action = request.create(saml_config(idp_entity_id), auth_params || {})
    if request.respond_to?(:request_id)
      session[:saml_transaction_id] = request.request_id
    end
    redirect_to action
  end

  # def create
  #   puts '----------------------------------------'
  #   puts 'SamlSessionsController "create"'
  #   puts '----------------------------------------'
  #   super
  # end


  # def create
  #   puts '----------------------------------------'
  #   puts 'SamlSessionsController "create"'
  #   puts '----------------------------------------'
  #   begin
  #     response = OneLogin::RubySaml::Response.new(params[:SAMLResponse], settings: saml_config)
  #     if response.is_valid?
  #       attribute_map = YAML.load(File.read("#{Rails.root}/config/attribute-map.yml"))
  #       attributes = Hash[response.attributes.map { |k, v| [attribute_map[k], v[0]] }]
  #       @user = User.load_saml_data attributes
  #       # session[:userid] = response.nameid
  #       # session[:attributes] = response.attributes
  #       # session[:userid] = @user.email
  #       session[:email] = @user.email
  #       if @user.persisted?
  #         flash[:notice] = 'Signed in successfully.'
  #         #sign_in_and_redirect @user #, :event => :authentication
  #         sign_in @user #, :event => :authentication
  #       end
  #     else
  #       raise 'Invalid response'
  #     end
  #   rescue Exception => e
  #     flash[:notice] = e.message
  #     redirect_to root_path
  #   end
  # end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || uke_regulations_path(locale: locale)
  end

  def metadata
    meta = OneLogin::RubySaml::Metadata.new
    render :xml => meta.generate(saml_config)
  end

  def idp_sign_out
    if params[:SAMLRequest] && Devise.saml_session_index_key
      saml_config = saml_config(get_idp_entity_id(params))
      logout_request = OneLogin::RubySaml::SloLogoutrequest.new(params[:SAMLRequest], settings: saml_config)
      # BJ 2019.09.24 
      #resource_class.reset_session_key_for(logout_request.name_id)
      resource_class.reset_session_key_for(logout_request.name_id.downcase)
      redirect_to generate_idp_logout_response(saml_config, logout_request.id)
    elsif params[:SAMLResponse]
      # Currently Devise handles the session invalidation when the request is made.
      # To support a true SP initiated logout response, the request ID would have to be tracked and session invalidated
      # based on that.
      if Devise.saml_sign_out_success_url
        redirect_to Devise.saml_sign_out_success_url
      else
        redirect_to action: :new
      end
    else
      head :invalid_request
    end
  end

  protected

  def relay_state
    @relay_state ||= if Devise.saml_relay_state.present?
      Devise.saml_relay_state.call(request)
    end
  end

  # For non transient name ID, save info to identify user for logout purpose
  # before that user's session got destroyed. These info are used in the
  # `after_sign_out_path_for` method below.
  def store_info_for_sp_initiated_logout
    return if Devise.saml_config.name_identifier_format == "urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
    @name_identifier_value_for_sp_initiated_logout = Devise.saml_name_identifier_retriever.call(current_user)
    @sessionindex_for_sp_initiated_logout = current_user.public_send(Devise.saml_session_index_key) if Devise.saml_session_index_key
  end

  # Override devise to send user to IdP logout for SLO
  def after_sign_out_path_for(_)
    idp_entity_id = get_idp_entity_id(params)
    request = OneLogin::RubySaml::Logoutrequest.new
    saml_settings = saml_config(idp_entity_id).dup

    # Add attributes to saml_settings which will later be used to create the SP
    # initiated logout request
    unless Devise.saml_config.name_identifier_format == 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient'
      saml_settings.name_identifier_value = @name_identifier_value_for_sp_initiated_logout
      saml_settings.sessionindex = @sessionindex_for_sp_initiated_logout
    end

    request.create(saml_settings)
  end

  # Overried devise: if user is signed out, not create the SP initiated logout request,
  # redirect to saml_sign_out_success_url,
  # or devise's after_sign_out_path_for
  def verify_signed_out_user
    if all_signed_out?
      set_flash_message! :notice, :already_signed_out

      redirect_to Devise.saml_sign_out_success_url.presence ||
                  Devise::SessionsController.new.after_sign_out_path_for(resource_name)
    end
  end

  def generate_idp_logout_response(saml_config, logout_request_id)

    params = {}
    if relay_state
      params[:RelayState] = relay_state
    end

    OneLogin::RubySaml::SloLogoutresponse.new.create(saml_config, logout_request_id, nil, params)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized, except: [:index, :datatables_index_role, :datatables_index_group, :datatables_index]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :account_off, :account_on, :set_activity_at]


  def datatables_index_role
    checked_filter = (params[:checked_only_filter].blank? || params[:checked_only_filter] == 'false' ) ? nil : true
    respond_to do |format|
      format.json { render json: RoleUsersDatatable.new(params, view_context: view_context, only_for_current_role_id: params[:role_id], checked_only_filter: checked_filter) }
    end
  end

  def datatables_index_group
    checked_filter = (params[:checked_only_filter].blank? || params[:checked_only_filter] == 'false' ) ? nil : true
    respond_to do |format|
      format.json { render json: GroupUsersDatatable.new(params, view_context: view_context, only_for_current_group_id: params[:group_id], checked_only_filter: checked_filter) }
    end
  end

  def datatables_index
    respond_to do |format|
      format.json { render json: UserDatatable.new(params, view_context: view_context) }
    end
  end

  def select2_index
    authorize :user, :index?
    #params[:q] = (params[:q]).upcase
    params[:q] = params[:q]
    @users = User.order(:email, :last_name, :first_name).finder_user(params[:q])
    @users_on_page = @users.page(params[:page]).per(params[:page_limit])
    
    render json: { 
      users: @users_on_page.as_json(methods: :fullname, only: [:id, :fullname]),
      meta: { total_count: @users.count }  
    } 
  end

  # GET /users
  # GET /users.json
  def index
    authorize :user, :index?
  end

  # GET /users/1
  # GET /users/1.json
  def show
    authorize @user, :show?
  end

  # GET /users/new
  def new
    @user = User.new
    authorize @user, :new?
  end

  # GET /users/1/edit
  def edit
    authorize @user, :edit?
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    authorize @user, :create?
    respond_to do |format|
      if @user.save
        @user.log_work('create', current_user.id)
        format.html { 
          flash[:success] = t('activerecord.successfull.messages.created', data: @user.fullname)
          redirect_to @user 
        }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    authorize @user, :update?
    respond_to do |format|
      if @user.update(user_params)
        @user.log_work('update', current_user.id)
        format.html { 
          flash[:success] = t('activerecord.successfull.messages.updated', data: @user.fullname)
          redirect_to @user 
        }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    authorize @user, :destroy?
    destroyed_clone = @user.clone
    if @user.destroy
      destroyed_clone.log_work('destroy', current_user.id)
      flash[:success] = t('activerecord.successfull.messages.destroyed', data: @user.fullname)
      redirect_to users_url
    else 
      flash.now[:error] = t('activerecord.errors.messages.destroyed', data: @user.fullname)
      #redirect_to :back
      render :show
    end      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      defaults = { author_id: "#{current_user.id}" }
      params.require(:user).permit(:email, :note, :author_id).reverse_merge(defaults)
      # params.require(:user).permit(:email, :note, :author_id, role_ids: []).reverse_merge(defaults).tap do |parameters|
        # raise
      # end
    end

end

# , examiners_attributes: [:id, :name, :_destroy]
#       params.require(:role).permit(:name, :note, :activities, :author_id).tap do |parameters|
#         parameters[:activities] = parameters[:activities].try(:split)
#       end

app/helpers/users_helper.rb
module UsersHelper

  ICON = "user"

  def user_icon_legend
    fa_icon(ICON)
  end

  def user_legend
    fa_icon(ICON, text: t("users.show.title"))
  end

  def user_show_legend
    fa_icon(ICON, text: t("users.show.title"))
  end

  def user_index_legend
    fa_icon(ICON, text: t("users.index.title"))
  end

  def user_edit_legend(data_obj=nil)
    data_obj.present? ? fa_icon(ICON, text: t("users.edit.title") + ": " + data_obj.fullname_was) : fa_icon(ICON, text: t("helpers.links.edit") )
  end

  def user_new_legend(data_obj=nil)
    data_obj.present? ? fa_icon(ICON, text: t("users.new.title") + ": " + data_obj.fullname) : fa_icon(ICON, text: t("helpers.links.new") )
  end

  def user_info_legend(data_obj)
    user_show_legend + ": " + data_obj.fullname
  end

end

app/views/users/_archives.html.erb
<div id="tab_archives">
  <fieldset class="my-fieldset">
    <legend class="my-fieldset colored-title"><%= subtitle %>&nbsp;&nbsp;-&nbsp;&nbsp;<%= archive_index_legend %></legend>

    <div class="row">
      <div class="col-sm-12">
        <table id="user-archives-table" class="hover cell-border compact" width="100%" 
          data-source="<%= datatables_index_user_archives_path(user_id: @user.id, format: :json) %>"
          data-locale_url="<%= datatables_lang_path(format: :json) %>">
          <thead>
            <tr>
              <th>ID</th>
              <th><%= Archive.human_attribute_name(:name) %></th>
              <th><%= Archive.human_attribute_name(:expiry_on) %></th>
              <th><%= Archive.human_attribute_name(:note) %></th>
              <th><%= t('table_group_archivization') %></th>
            </tr>
          </thead>
          <tbody>
             <!--data from JSON -->
          </tbody>
        </table>
      </div> <!--/col-sm-12 -->
    </div> <!--/row -->

  </fieldset>
</div>

app/views/users/_data.html.erb
<div id="tab_data">
  <fieldset class="my-fieldset">
    <legend class="my-fieldset colored-title"><%= subtitle %></legend>
    <div class="row">

      <div class="col-sm-12">
        <% input_disabled ||= false  
           #if input_disabled is not passed to the partial it doesn't crash. 
           # We default it to false 
        %>

        <%= form_errors_for @user %>

        <div class="row">
          <div class="col-sm-6">
            <div class="row">

              <div class="form-group col-sm-6">
                <p><strong><%= User.human_attribute_name(:user_name) %></strong></p>
                <%= @user.user_name %>
              </div>

              <div class="form-group col-sm-6">
                <p><strong><%= User.human_attribute_name(:email) %></strong></p>
                <%= @user.email %>
              </div>

              <div class="form-group col-sm-6">
                <p><strong><%= User.human_attribute_name(:first_name) %></strong></p>
                <%= @user.first_name %>
              </div>

              <div class="form-group col-sm-6">
                <p><strong><%= User.human_attribute_name(:last_name) %></strong></p>
                <%= @user.last_name %>
              </div>

            </div>  <!-- /row -->
          </div>  <!-- /col-sm-6 -->

          <div class="col-sm-6">
            <div class="row">
              <div class="form-group col-sm-12">
<!-- 
                <p><strong><%= User.human_attribute_name(:note) %></strong></p>
                <%= @user.note.html_safe %>
                <%#= text_with_break_line(@user.note) %>
 -->
                <% if @user.note.html_safe.size > 0 %>
                  <blockquote>
                    <%= @user.note.html_safe %>
                  </blockquote>
                <% end %>
              </div>
            </div>
          </div> <!--/col-sm-6 -->
        </div>  <!-- /row -->

        <div class="row">
          <div class="col-sm-12">
            <div class="row">

              <div class="form-group col-sm-3">
                <p><strong><%= User.human_attribute_name(:last_sign_in_at) %></strong></p>
                <%= @user.last_sign_in_at.strftime("%Y-%m-%d %H:%M:%S") if @user.last_sign_in_at.present? %>
              </div>
              <div class="form-group col-sm-3">
                <p><strong><%= User.human_attribute_name(:last_sign_in_ip) %></strong></p>
                <%= @user.last_sign_in_ip if @user.last_sign_in_ip.present? %>
              </div>

              <div class="form-group col-sm-3">
                <p><strong><%= User.human_attribute_name(:current_sign_in_at) %></strong></p>
                <%= @user.current_sign_in_at.strftime("%Y-%m-%d %H:%M:%S") if @user.current_sign_in_at.present? %>
              </div>
              <div class="form-group col-sm-3">
                <p><strong><%= User.human_attribute_name(:current_sign_in_ip) %></strong></p>
                <%= @user.current_sign_in_ip if @user.current_sign_in_ip.present? %>
              </div>

            </div>

          </div> <!-- /col-sm-12 -->
        </div> <!-- /row -->

        <hr class="hr-without-top-margin">

        <div class="row">
          <div class="col-sm-12">
<!-- 
            <%#= link_to users_path, class: "btn btn-default" do %>
              <span class="fa fa-list"></span>
              <%#= t("helpers.links.index") %>
            <%# end %>
 -->
            <% if policy(@user).destroy? %>
              <%= link_to user_path(@user),
                                  method: :delete,
                                  data: { confirm: t('helpers.links.confirm_destroy', data: @user.fullname) }, 
                                  class: "btn btn-danger" do %>
                <span class="fa fa-trash"></span>
                <%= t("helpers.links.destroy") %>
              <% end %>
            <% end %>

            <% if policy(@user).edit? %>
              <%= link_to edit_user_path(@user), class: "btn btn-primary" do %>
                <span class="fa fa-edit"></span>
                <%= t("helpers.links.edit") %>
              <% end %>
            <% end %>

            <h6 class="pull-right"><%= last_updated_legend(@user) %></h6>

          </div> <!--/col-sm-12 -->
        </div> <!-- /row -->

      </div> <!--/col-sm-12-->  

    </div>
  </fieldset>
</div>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <%= form_with(model: user, local: true) do |f| %>

      <% input_disabled ||= false  
         #if input_disabled is not passed to the partial it doesn't crash. 
         # We default it to false 
      %>

      <%= form_errors_for user %>

      <div class="row">
        <div class="col-sm-6">
          <div class="row">

            <div class="form-group col-sm-6">
              <%= f.label :user_name, class: 'control-label' %>
              <%= f.text_field :user_name, class: 'form-control input-sm', disabled: input_disabled %>
            </div>

            <div class="form-group col-sm-6">
              <%= f.label :email, class: 'control-label' %>
              <%= f.text_field :email, autofocus: true, class: 'form-control input-sm', disabled: !user.new_record? %>
            </div>

            <div class="form-group col-sm-6">
              <%= f.label :first_name, class: 'control-label' %>
              <%= f.text_field :first_name, class: 'form-control input-sm', disabled: input_disabled %>
            </div>

            <div class="form-group col-sm-6">
              <%= f.label :last_name, class: 'control-label' %>
              <%= f.text_field :last_name, class: 'form-control input-sm', disabled: input_disabled %>
            </div>

          </div>  <!-- /row -->
        </div>  <!-- /col-sm-6 -->

        <div class="col-sm-6">
          <div class="row">
            <div class="form-group col-sm-12">
              <%= f.label :note, class: 'control-label' %>
              <%= f.trix_editor :note %>
              <%#= f.text_area :note, :rows => 4, class: 'form-control input-sm' %>
            </div>
          </div> <!-- /row -->
        </div> <!--/col-sm-6 -->

      </div>  <!-- /row -->


      <hr class="hr-without-top-margin">

      <div class="row">
        <div class="col-sm-12">

          <%= link_to user.new_record? ? users_path() : user_path(user), class: "btn btn-default" do %>
            <%= back_from_new_or_edit_legend %>
          <% end %>

          <%= f.submit nil, class: 'btn btn-success' %>

        </div> <!--/col-sm-12 -->
      </div> <!-- /row -->
      
    <% end %>

  </div> <!--/col-sm-11-->
</div>

app/views/users/_groups.html.erb
<div id="tab_groups">
  <fieldset class="my-fieldset">
    <legend class="my-fieldset colored-title"><%= subtitle %>&nbsp;&nbsp;-&nbsp;&nbsp;<%= group_index_legend %></legend>

    <div class="row">
      <div class="col-sm-12">
        <table id="user-groups-table" class="hover cell-border compact" width="100%" 
          data-source="<%= datatables_index_user_groups_path(user_id: @user.id, format: :json) %>"
          data-locale_url="<%= datatables_lang_path(format: :json) %>">
          <thead>
            <tr>
              <th>ID</th>
              <th><%= Group.human_attribute_name(:name) %></th>
              <th><%= Group.human_attribute_name(:note) %></th>
              <th><%= t('table_group_member') %></th>
              <th><%= t('table_action') %></th>
            </tr>
          </thead>
          <tbody>
             <!--data from JSON -->
          </tbody>
        </table>
      </div> <!--/col-sm-12 -->
    </div> <!--/row -->

  </fieldset>
</div>

app/views/users/_roles.html.erb
<div id="tab_roles">
  <fieldset class="my-fieldset">
    <legend class="my-fieldset colored-title"><%= subtitle %>&nbsp;&nbsp;-&nbsp;&nbsp;<%= role_index_legend %></legend>

    <div class="row">
      <div class="col-sm-12">
        <table id="user-roles-table" class="hover cell-border compact" width="100%" 
          data-source="<%= datatables_index_user_roles_path(user_id: @user.id, format: :json) %>"
          data-locale_url="<%= datatables_lang_path(format: :json) %>">
          <thead>
            <tr>
              <th>ID</th>
              <th><%= Role.human_attribute_name(:name) %></th>
              <th><%= Role.human_attribute_name(:activities) %></th>
              <th><%= t('table_role_granted') %></th>
              <th><%= t('table_action') %></th>
            </tr>
          </thead>
          <tbody>
             <!--data from JSON -->
          </tbody>
        </table>
      </div> <!--/col-sm-12 -->
    </div> <!--/row -->

  </fieldset>
</div>

app/views/users/_sidebar_edit.html.erb
<button class="sideber-button fa fa-chevron-right" onclick="changeSidebar(this)" title="<%=t('sidebar')%>" rel='tooltip'></button>

<div class="sidebar-content-small container-fluid">
  <div class="center"><%= user_icon_legend %></div>
  <hr>

  <div class="row">
    <div class="col-sm-12">

      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">

        <li role="presentation" class="brand-nav"><%= link_to users_path, title: t('.index'), rel: 'tooltip' do %>
          <span class="fa fa-list"></span>
          <% end %>
        </li>

      </ul>

    </div>
  </div>

</div>    


<div class="sidebar-content-large hidden container-fluid">
  <div class="center"><%= user_legend %></div>
  <hr>
  <div class="row">
    <div class="col-sm-12">


      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">
 
        <li role="presentation" class="brand-nav"><%= link_to users_path, title: t('.index'), rel: 'tooltip' do %>
            <%= back_to_index_legend %>
          <% end %>
        </li>

      </ul>


    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-sm-12">
      <div class="center"><%= fa_icon("edit", size: '2x') %></div>
      <h3 class="center"><%= t('helpers.links.edit') %></h3>
    </div>
  </div>


</div>

app/views/users/_user.html.erb
<td class="col-md-5">
  <%= user.name_as_link %>
</td>
<td class="col-md-7">
  <%= user.flat_assigned_projects %>
</td>

app/views/users/index.html.erb
<div class="grid-container">

  <div class="sidebar">
    <%= render 'sidebar_index' %>
  </div>

  <div class="main-content">
    <div class="container-fluid">

      <div class="row">
        <div class="col-sm-12">
          <h3 class="center colored-title index-title"><%= user_index_legend %></h3>
        </div> <!--/col-sm-12 -->
      </div> <!--/row -->

      <div class="row">
        <div class="col-sm-12">
          <table id="users-table" class="hover cell-border" cellspacing="0" width="100%" 
            data-source="<%= datatables_index_users_path(format: :json) %>",
            data-locale_url="<%= datatables_lang_path(format: :json) %>">
            <thead>
              <tr>
                <th>ID</th>
                <th><%= User.human_attribute_name(:email) %></th>
                <th><%= User.human_attribute_name(:last_name) %></th>
                <th><%= User.human_attribute_name(:first_name) %></th>
                <th><%= User.human_attribute_name(:note) %></th>
                <th><%= User.human_attribute_name(:current_sign_in_ip) %></th>
                <th><%= User.human_attribute_name(:current_sign_in_at) %></th>
              </tr>
            </thead>
            <tbody>
              <!-- data from ajax -->
            </tbody>
          </table>
        </div> <!--/col-sm-12 -->
      </div> <!--/row -->

    </div> <!--/container-fluid--> 
  </div> <!--/main-content--> 

</div> <!--/grid-containe--> 