config/routes.rb
Rails.application.routes.draw do

#          new_user_session GET      /users/saml/sign_in(.:format)                       devise/saml_sessions#new
#              user_session POST     /users/saml/auth(.:format)                          devise/saml_sessions#create
#      destroy_user_session DELETE   /users/sign_out(.:format)                           devise/saml_sessions#destroy
#     metadata_user_session GET      /users/saml/metadata(.:format)                      devise/saml_sessions#metadata
# idp_sign_out_user_session GET|POST /users/saml/idp_sign_out(.:format)                  devise/saml_sessions#idp_sign_out


  devise_for :users, controllers: {
    saml_sessions: 'users/saml_sessions'
  }

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

    resources :uke_regulations, only: [:index]

    resources :works, only: [:index] do
      post 'datatables_index', on: :collection # for User
      post 'datatables_index_trackable', on: :collection # for Trackable
      post 'datatables_index_user', on: :collection # for User
    end

    resources :users do
      get 'select2_index', on: :collection
      post 'datatables_index', on: :collection
      get 'datatables_index_role', on: :collection # Displays users for showed role
      get 'datatables_index_group', on: :collection # Displays users for showed group
      resources :attachments, module: :users, only: [:create] do
        post 'create_folder', on: :collection
      end
    end

    resources :roles do
      post 'datatables_index', on: :collection
      get 'datatables_index_user', on: :collection # Displays roles for showed user
      resources :users, only: [:create, :destroy], controller: 'roles/users'
    end    

    resources :groups do
      get 'select2_index', on: :collection
      post 'datatables_index', on: :collection
      get 'datatables_index_user', on: :collection # Displays groups for showed user
      resources :users, only: [:create, :destroy], controller: 'groups/users'
    end    

    resources :archives do
      post 'datatables_index', on: :collection
      get 'datatables_index_group', on: :collection # Displays archives for showed group
      get 'datatables_index_user', on: :collection # Displays archives for showed user
      get 'help_new_edit', on: :collection
      post 'send_link_to_archive_show', on: :member
      resources :components, module: :archives, only: [:create] do
        post 'create_folder', on: :collection
      end
    end

    resources :components, except: [:create] do 
      get 'datatables_index', on: :collection # for Trackable
      get 'zip_and_download', on: :collection
      patch 'move_to_parent', on: :collection
      get 'download', on: :member
      get 'download_simple', on: :member
      post 'send_link_to_component_download', on: :member
      post 'send_link_to_component_download_simple', on: :member
    end

    get 'datatables/lang'
    get 'static_pages/home'
    get 'static_pages/declaration'

    root to: 'static_pages#home'
	end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  # get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302),
  #               constraints: { path: /(?!(#{I18n.available_locales.join("|")})\/).*/ },
  #               format: false


  namespace :api, defaults: { format: :json } do
    require 'api_constraints'
    namespace :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      get :token, controller: 'base_api'

    end

    namespace :v2 do
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
  include ActionView::Helpers::TextHelper # for truncate

  delegate :url_helpers, to: 'Rails.application.routes'


  # relations
  has_many :approvals, dependent: :destroy
  has_many :users, through: :approvals


  belongs_to :author, class_name: "User"
  has_many :works, as: :trackable

  # validates
  validates :name, presence: true,
                    length: { in: 1..100 },
                    uniqueness: { case_sensitive: false }

  validates :note, length: { in: 0..500 }

  # callbacks


  def log_work(action = '', action_user_id = nil)
    worker_id = action_user_id || self.author_id
    url = "<a href=#{url_helpers.role_path(self.id, locale: :pl)}>#{self.fullname}</a>".html_safe

    Work.create!(trackable_type: 'Role', trackable_id: self.id, action: "#{action}", author_id: worker_id, url: "#{url}", 
      parameters: self.to_json(except: [:author_id], include: {author: {only: [:id, :user_name, :email]}}))
  end

  def fullname
    "#{name}"
  end

  def fullname_was
    "#{name_was}"
  end

  def note_truncate
    truncate(Loofah.fragment(self.note).text, length: 100)
  end

  private
  

end

app/controllers/roles/users_controller.rb
class Roles::UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def create
    role = Role.find(params[:role_id])
    user = User.find(params[:id])

    authorize role, :add_remove_role_user? 

    approval = Approval.create!(role: role, user: user, author: current_user)
    approval.log_work_for_user('add_role_to_user', current_user.id)
    approval.log_work_for_role('add_user_to_role', current_user.id)

    head :ok
  end

  def destroy
    role = Role.find(params[:role_id])
    user = User.find(params[:id])

    authorize role, :add_remove_role_user? 

    if role.present? && user.present?
      approval = Approval.find_by(role: role, user: user)
      destroyed_clone = approval.clone
      if approval.destroy
        destroyed_clone.log_work_for_user('remove_role_from_user', current_user.id)
        destroyed_clone.log_work_for_role('remove_user_from_role', current_user.id)
      end
    end

    head :no_content
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized, except: [:index, :datatables_index, :datatables_index_user]
  before_action :set_role, only: [:show, :edit, :update, :destroy]


  def datatables_index_user
    checked_filter = (params[:checked_only_filter].blank? || params[:checked_only_filter] == 'false' ) ? nil : true
    respond_to do |format|
      format.json{ render json: UserRolesDatatable.new(params, view_context: view_context, only_for_current_user_id: params[:user_id], checked_only_filter: checked_filter) }
    end
  end

  def datatables_index
    respond_to do |format|
      format.json{ render json: RoleDatatable.new(params, view_context: view_context) }
    end
  end

  # GET /roles
  # GET /roles.json
  def index
    authorize :role, :index?
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    authorize @role, :show?
  end

  # GET /roles/new
  def new
    @role = Role.new
    @role.author = current_user
    authorize @role, :new?
  end

  # GET /roles/1/edit
  def edit
    authorize @role, :edit?
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)
    @role.author = current_user
    authorize @role, :create?
    respond_to do |format|
      if @role.save
        @role.log_work('create', current_user.id)
        flash[:success] = t('activerecord.successfull.messages.created', data: @role.fullname)
        format.html { redirect_to @role }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    @role.author = current_user
    authorize @role, :update?
    respond_to do |format|
      if @role.update(role_params)
        @role.log_work('update', current_user.id)
        flash[:success] = t('activerecord.successfull.messages.updated', data: @role.fullname)
        format.html { redirect_to @role }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    authorize @role, :destroy?
    destroyed_clone = @role.clone
    if @role.destroy
      destroyed_clone.log_work('destroy', current_user.id)
      flash[:success] = t('activerecord.successfull.messages.destroyed', data: @role.fullname)
      redirect_to roles_url
    else 
      flash.now[:error] = t('activerecord.errors.messages.destroyed', data: @role.fullname)
      #redirect_to :back
      render :show
    end      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :note, :activities, :author_id).tap do |parameters|
        parameters[:activities] = parameters[:activities].try(:split)
      end
    end
end

app/helpers/roles_helper.rb
module RolesHelper

  ICON = "user-tag"

  def role_icon_legend
    fa_icon(ICON)
  end

  def role_legend
    fa_icon(ICON, text: t("roles.show.title"))
  end

  def role_show_legend
    fa_icon(ICON, text: t("roles.show.title"))
  end

  def role_index_legend
    fa_icon(ICON, text: t("roles.index.title"))
  end

  def role_edit_legend(data_obj=nil)
    data_obj.present? ? fa_icon(ICON, text: t("roles.edit.title") + ": " + data_obj.fullname_was) : fa_icon(ICON, text: t("helpers.links.edit") )
  end

  def role_new_legend(data_obj=nil)
    data_obj.present? ? fa_icon(ICON, text: t("roles.new.title") + ": " + data_obj.fullname) : fa_icon(ICON, text: t("helpers.links.new") )
  end

  def role_info_legend(data_obj)
    role_show_legend + ": " + data_obj.fullname
  end

end

app/views/roles/_data.html.erb
<div id="tab_data">
  <fieldset class="my-fieldset">
    <legend class="my-fieldset colored-title"><%= subtitle %></legend>
    <div class="row">

      <div class="col-sm-12">
        <% input_disabled ||= false  
           #if input_disabled is not passed to the partial it doesn't crash. 
           # We default it to false 
        %>

        <%= form_errors_for @role %>

        <div class="row">
          <div class="col-sm-6">
            <div class="row">

              <div class="form-group col-sm-12">
                <p><strong><%= Role.human_attribute_name(:name) %></strong></p>
                <%= @role.name %>
              </div>

            </div>  <!-- /row -->
          </div>  <!-- /col-sm-6 -->

          <div class="col-sm-6">
            <div class="row">
              <div class="form-group col-sm-12">
<!-- 
                <p><strong><%= Role.human_attribute_name(:note) %></strong></p>
                <%= @role.note.html_safe %>
 -->
                <% if @role.note.html_safe.size > 0 %>
                  <blockquote>
                    <%= @role.note.html_safe %>
                  </blockquote>
                <% end %>
              </div>
            </div>
          </div> <!--/col-sm-6 -->
        </div>  <!-- /row -->

        <div class="row">
          <div class="col-sm-12">
            <div class="row">

              <div class="form-group col-sm-12">
                <p><strong><%= Role.human_attribute_name(:activities) %></strong></p>
                <%= @role.activities %>
              </div>

            </div> <!-- /row -->
          </div> <!--/col-sm-12 -->
        </div>  <!-- /row -->

        <hr class="hr-without-top-margin">

        <div class="row">
          <div class="col-sm-12">
<!-- 
            <%#= link_to roles_path, class: "btn btn-default" do %>
              <span class="fa fa-list"></span>
              <%#= t("helpers.links.index") %>
            <%# end %>
 -->
            <% if policy(@role).destroy? %>
              <%= link_to role_path(@role),
                                  method: :delete,
                                  data: { confirm: t('helpers.links.confirm_destroy', data: @role.name) }, 
                                  class: "btn btn-danger" do %>
                <span class="fa fa-trash"></span>
                <%= t("helpers.links.destroy") %>
              <% end %>
            <% end %>

            <% if policy(@role).edit? %>
              <%= link_to edit_role_path(@role), class: "btn btn-primary" do %>
                <span class="fa fa-edit"></span>
                <%= t("helpers.links.edit") %>
              <% end %>
            <% end %>

            <h6 class="pull-right"><%= last_updated_legend(@role) %></h6>

          </div> <!--/col-sm-12 -->
        </div> <!-- /row -->


      </div> <!--/col-sm-12-->  

    </div>
  </fieldset>
</div>

app/views/roles/_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <%= form_with(model: role, local: true) do |f| %>

      <% input_disabled ||= false  
         #if input_disabled is not passed to the partial it doesn't crash. 
         # We default it to false 
      %>

      <%= form_errors_for role %>

      <div class="row">
        <div class="col-sm-6">
          <div class="row">

            <div class="form-group required col-sm-12">
              <%= f.label :name, class: 'control-label' %>
              <%= f.text_field :name, autofocus: true, class: 'form-control input-sm', disabled: input_disabled %>
            </div>

          </div>  <!-- /row -->
        </div>  <!-- /col-sm-6 -->


        <div class="col-sm-6">
          <div class="row">
            <div class="form-group col-sm-12">
              <%= f.label :note, class: 'control-label' %>
              <%= f.trix_editor :note %>
            </div>
          </div> <!-- /row -->
        </div> <!--/col-sm-6 -->

      </div>  <!-- /row -->

      <div class="row">
        <div class="col-sm-12">
          <div class="row">

            <div class="form-group col-sm-12">
              <%= f.label :activities %>
              <%= f.text_field :activities, class: 'form-control input-sm', disabled: input_disabled %>
            </div>

          </div> <!-- /row -->
        </div> <!--/col-sm-12 -->
      </div>  <!-- /row -->


      <hr class="hr-without-top-margin">

      <div class="row">
        <div class="col-sm-12">

          <%= link_to role.new_record? ? roles_path() : role_path(role), class: "btn btn-default" do %>
            <%= back_from_new_or_edit_legend %>
          <% end %>

          <%= f.submit nil, class: 'btn btn-success' %>

        </div> <!--/col-sm-12 -->
      </div> <!-- /row -->
      
    <% end %>

  </div> <!--/col-sm-12-->
</div>

app/views/roles/_role.html.erb
<td class="col-md-2">
  <%= role.name_as_link %>
</td>
<td class="col-md-6">
  <%= role.activities %>
</td>
<td class="col-md-3">
  <%= truncate(role.note, length: 50) %>
</td>
<!--
<td>
  <%#= link_to("Delete role", role_path(role), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs-danger') %>
</td>
-->

app/views/roles/_sidebar_edit.html.erb
<button class="sideber-button fa fa-chevron-right" onclick="changeSidebar(this)" title="<%=t('sidebar')%>" rel='tooltip'></button>

<div class="sidebar-content-small container-fluid">
  <div class="center"><%= role_icon_legend %></div>
  <hr>

  <div class="row">
    <div class="col-sm-12">

      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">

        <li role="presentation" class="brand-nav"><%= link_to roles_path, title: t('.index'), rel: 'tooltip' do %>
          <span class="fa fa-list"></span>
          <% end %>
        </li>

      </ul>

    </div>
  </div>

</div>    


<div class="sidebar-content-large hidden container-fluid">
  <div class="center"><%= role_legend %></div>
  <hr>
  <div class="row">
    <div class="col-sm-12">


      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">
 
        <li role="presentation" class="brand-nav"><%= link_to roles_path, title: t('.index'), rel: 'tooltip' do %>
            <%= back_to_index_legend %>
          <% end %>
        </li>

      </ul>


    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-sm-12">
      <div class="center"><%= fa_icon("edit", size: '2x') %></div>
      <h3 class="center"><%= t('helpers.links.edit') %></h3>
    </div>
  </div>


</div>

app/views/roles/_sidebar_index.html.erb
<button class="sideber-button fa fa-chevron-right" onclick="changeSidebar(this)" title="<%=t('sidebar')%>" rel='tooltip'></button>

<div class="sidebar-content-small container-fluid">
  <div class="center"><%= role_icon_legend %></div>
  <hr>
   
  <div class="row">
    <div class="col-sm-12">

      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">

        <% if policy(:role).new? %>
          <li role="presentation" class="brand-nav"><%= link_to new_role_path, title: t('.new'), rel: 'tooltip' do %>
              <span class="fa fa-plus"></span>
            <% end %>
          </li>
        <% end %>

      </ul>

    </div>
  </div>

</div>    


<div class="sidebar-content-large hidden container-fluid">
  <div class="center"><%= role_index_legend %></div>
  <hr>
  <div class="row">
    <div class="col-sm-12">

      <% if policy(:role).new? %>
        <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">
   
          <li role="presentation" class="brand-nav"><%= link_to new_role_path, title: t('.new'), rel: 'tooltip' do %>
            <span class="fa fa-plus"></span>
            <%= t('helpers.links.new') %>
            <% end %>
          </li>

        </ul>

      <% end %>

    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-sm-12">
      <div class="center"><%= fa_icon("list", size: '2x') %></div>
      <h3 class="center"><%= t('helpers.links.index') %></h3>
    </div>
  </div>

</div>

app/views/roles/_sidebar_new.html.erb
<button class="sideber-button fa fa-chevron-right" onclick="changeSidebar(this)" title="<%=t('sidebar')%>" rel='tooltip'></button>

<div class="sidebar-content-small container-fluid">
  <div class="center"><%= role_icon_legend %></div>
  <hr>

  <div class="row">
    <div class="col-sm-12">

      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">

        <li role="presentation" class="brand-nav"><%= link_to roles_path, title: t('.index'), rel: 'tooltip' do %>
          <span class="fa fa-list"></span>
          <% end %>
        </li>

      </ul>

    </div>
  </div>

</div>    


<div class="sidebar-content-large hidden container-fluid">
  <div class="center"><%= role_legend %></div>
  <hr>
  <div class="row">
    <div class="col-sm-12">


      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">
 
        <li role="presentation" class="brand-nav"><%= link_to roles_path, title: t('.index'), rel: 'tooltip' do %>
            <%= back_to_index_legend %>
          <% end %>
        </li>

      </ul>


    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-sm-12">
      <div class="center"><%= fa_icon("plus", size: '2x') %></div>
      <h3 class="center"><%= t('helpers.links.new') %></h3>
    </div>
  </div>


</div>

app/views/roles/_sidebar_show.html.erb
<button class="sideber-button fa fa-chevron-right" onclick="changeSidebar(this)" title="<%=t('sidebar')%>" rel='tooltip'></button>

<div class="sidebar-content-small container-fluid">
  <div class="center"><%= role_icon_legend %></div>
  <hr>

  <div class="row">
    <div class="col-sm-12">

      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">

        <li role="presentation" class="brand-nav active" title="<%= t('helpers.links.show') %>" rel='tooltip'>
          <a href="#role_show" aria-controls="role_show" role="tab" data-toggle="tab"><%= role_icon_legend %></a>
        </li>

        <% if policy(:user).index? %>
          <li role="presentation" class="brand-nav" title="<%= t('users.index.title') %>" rel='tooltip'>
            <a href="#users" aria-controls="users" role="tab" data-toggle="tab"><%= user_icon_legend %></a>
          </li>
        <% end %>

        <% if policy(:role).work? %>
          <li role="presentation" class="brand-nav" title="<%= t('works.index.title') %>" rel='tooltip'>
            <a href="#works" aria-controls="works" role="tab" data-toggle="tab"><%= work_icon_legend %></a>
          </li>
        <% end %>

        <hr>
        <li role="presentation" class="brand-nav"><%= link_to roles_path, title: t('.index'), rel: 'tooltip' do %>
          <span class="fa fa-list"></span>
          <% end %>
        </li>

      </ul>

    </div>
  </div>

</div>    


<div class="sidebar-content-large hidden container-fluid">
  <div class="center"><%= role_legend %></div>
  <hr>
  <div class="row">
    <div class="col-sm-12">

      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">

        <li role="presentation" class="brand-nav active" title="<%= t('helpers.links.show') %>" rel='tooltip'>
          <a href="#role_show" aria-controls="role_show" role="tab" data-toggle="tab"><%= role_show_legend %></a>
        </li>

        <% if policy(:user).index? %>
          <li role="presentation" class="brand-nav brand-nav-level-1" title="<%= t('users.index.title') %>" rel='tooltip'>
            <a href="#users" aria-controls="users" role="tab" data-toggle="tab"><%= user_index_legend %></a>
          </li>
        <% end %>

        <% if policy(:role).work? %>
          <li role="presentation" class="brand-nav brand-nav-level-1" title="<%= t('works.index.title') %>" rel='tooltip'>
            <a href="#works" aria-controls="works" role="tab" data-toggle="tab"><%= work_index_legend %></a>
          </li>
        <% end %>  

        <hr>
        <li role="presentation" class="brand-nav"><%= link_to roles_path, title: t('.index'), rel: 'tooltip' do %>
            <%= back_to_index_legend %>
          <% end %>
        </li>

      </ul>

    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-sm-12">
      <div class="center"><%= fa_icon("eye", size: '2x') %></div>
      <h3 class="center"><%= t('helpers.links.show') %></h3>
    </div>
  </div>


</div>

app/views/roles/_users.html.erb
<div id="tab_users">
  <fieldset class="my-fieldset">
    <legend class="my-fieldset colored-title"><%= subtitle %>&nbsp;&nbsp;-&nbsp;&nbsp;<%= user_index_legend %></legend>

    <div class="row">
      <div class="col-sm-12">
        <table id="role-users-table" class="hover cell-border compact" width="100%" 
          data-source="<%= datatables_index_role_users_path(role_id: @role.id, format: :json) %>",
          data-locale_url="<%= datatables_lang_path(format: :json) %>">
          <thead>
            <tr>
              <th>ID</th>
              <th><%= User.human_attribute_name(:email) %></th>
              <th><%= User.human_attribute_name(:last_name) %></th>
              <th><%= User.human_attribute_name(:first_name) %></th>
              <th><%= User.human_attribute_name(:note) %></th>
              <th><%= t('table_role_granted') %></th>
              <th><%= t('table_action') %></th>
            </tr>
          </thead>
          <tbody>
             <!--data from JSON -->
          </tbody>
        </table>
      </div> <!--/col-sm-12 -->
    </div> <!--/row -->

  </fieldset>
</div>

app/views/roles/edit.html.erb
<div class="grid-container">

  <div class="sidebar">
    <%= render 'sidebar_edit' %>
  </div>

  <div class="main-content">
    <br>
    <div class="container-fluid"> 
      <div class="row">
        <div class="col-sm-12">
          <fieldset class="my-fieldset">
            <legend class="my-fieldset colored-title"><%= role_edit_legend(@role) %></legend>
            <%= render 'form', role: @role %>
          </fieldset>
        </div>
      </div>

    </div> <!--/container-fluid--> 
  </div> <!--/main-content--> 

</div> <!--/grid-containe--> 

app/views/roles/index.html.erb
<div class="grid-container">

  <div class="sidebar">
    <%= render 'sidebar_index' %>
  </div>

  <div class="main-content">
    <div class="container-fluid">

      <div class="row">
        <div class="col-sm-12">
          <h3 class="center colored-title index-title"><%= role_index_legend %></h3>
        </div> <!--/col-sm-12 -->
      </div> <!--/row -->

      <div class="row">
        <div class="col-sm-12">
          <table id="roles-table" class="hover cell-border" cellspacing="0" width="100%" 
            data-source="<%= datatables_index_roles_path(format: :json) %>"
            data-locale_url="<%= datatables_lang_path(format: :json) %>">
            <thead>
              <tr>
                <th>ID</th>
                <th><%= Role.human_attribute_name(:name) %></th>
                <th><%= Role.human_attribute_name(:note) %></th>
                <th><%= Role.human_attribute_name(:activities) %></th>
              </tr>
            </thead>
            <tbody>
              <!-- data from ajax -->
            </tbody>
          </table>
          </table>
        </div> <!--/col-sm-12 -->
      </div> <!--/row -->

    </div> <!--/container-fluid--> 
  </div> <!--/main-content--> 

</div> <!--/grid-containe--> 

app/views/roles/new.html.erb
<div class="grid-container">

  <div class="sidebar">
    <%= render 'sidebar_new' %>
  </div>

  <div class="main-content">
    <br>
    <div class="container-fluid"> 
      <div class="row">
        <div class="col-sm-12">
          <fieldset class="my-fieldset">
            <legend class="my-fieldset colored-title"><%= role_new_legend(@role) %></legend>
            <%= render 'form', role: @role %>
          </fieldset>
        </div>
      </div>

    </div> <!--/container-fluid--> 
  </div> <!--/main-content--> 

</div> <!--/grid-containe--> 

app/views/roles/show.html.erb
<div class="grid-container">

  <div class="sidebar">
    <%= render 'sidebar_show' %>
  </div>

  <div class="main-content">
    <br>
    <div class="container-fluid"> 
      <div class="row">

        <div class="col-sm-12">
          <div class="tab-content clearfix">

            <div role="tabpanel" class="tab-pane active" id="role_show">
              <%= render 'data', input_disabled: true, subtitle: role_info_legend(@role) %>
            </div>

            <div role="tabpanel" class="tab-pane" id="users">
              <%= render 'users', subtitle: role_info_legend(@role) %>
            </div>

            <div role="tabpanel" class="tab-pane" id="works">
              <%= render 'works/works_tab', trackable_type: "Role", trackable_id: @role.id, subtitle: role_info_legend(@role) %>
            </div>

          </div>
        </div>

      </div>

    </div> <!--/container-fluid--> 
  </div> <!--/main-content--> 

</div> <!--/grid-containe--> 