config/routes.rb
Rails.application.routes.draw do

#          new_user_session GET      /users/saml/sign_in(.:format)                       devise/saml_sessions#new
#              user_session POST     /users/saml/auth(.:format)                          devise/saml_sessions#create
#      destroy_user_session DELETE   /users/sign_out(.:format)                           devise/saml_sessions#destroy
#     metadata_user_session GET      /users/saml/metadata(.:format)                      devise/saml_sessions#metadata
# idp_sign_out_user_session GET|POST /users/saml/idp_sign_out(.:format)                  devise/saml_sessions#idp_sign_out


  devise_for :users, controllers: {
    saml_sessions: 'users/saml_sessions'
  }

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

    resources :uke_regulations, only: [:index]

    resources :works, only: [:index] do
      post 'datatables_index', on: :collection # for User
      post 'datatables_index_trackable', on: :collection # for Trackable
      post 'datatables_index_user', on: :collection # for User
    end

    resources :users do
      get 'select2_index', on: :collection
      post 'datatables_index', on: :collection
      get 'datatables_index_role', on: :collection # Displays users for showed role
      get 'datatables_index_group', on: :collection # Displays users for showed group
      resources :attachments, module: :users, only: [:create] do
        post 'create_folder', on: :collection
      end
    end

    resources :roles do
      post 'datatables_index', on: :collection
      get 'datatables_index_user', on: :collection # Displays roles for showed user
      resources :users, only: [:create, :destroy], controller: 'roles/users'
    end    

    resources :groups do
      get 'select2_index', on: :collection
      post 'datatables_index', on: :collection
      get 'datatables_index_user', on: :collection # Displays groups for showed user
      resources :users, only: [:create, :destroy], controller: 'groups/users'
    end    

    resources :archives do
      post 'datatables_index', on: :collection
      get 'datatables_index_group', on: :collection # Displays archives for showed group
      get 'datatables_index_user', on: :collection # Displays archives for showed user
      get 'help_new_edit', on: :collection
      post 'send_link_to_archive_show', on: :member
      resources :components, module: :archives, only: [:create] do
        post 'create_folder', on: :collection
      end
    end

    resources :components, except: [:create] do 
      get 'datatables_index', on: :collection # for Trackable
      get 'zip_and_download', on: :collection
      patch 'move_to_parent', on: :collection
      get 'download', on: :member
      get 'download_simple', on: :member
      post 'send_link_to_component_download', on: :member
      post 'send_link_to_component_download_simple', on: :member
    end

    get 'datatables/lang'
    get 'static_pages/home'
    get 'static_pages/declaration'

    root to: 'static_pages#home'
	end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  # get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302),
  #               constraints: { path: /(?!(#{I18n.available_locales.join("|")})\/).*/ },
  #               format: false


  namespace :api, defaults: { format: :json } do
    require 'api_constraints'
    namespace :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      get :token, controller: 'base_api'

    end

    namespace :v2 do
    end
  end
end

app/models/archive.rb
require 'my_human'

class Archive < ApplicationRecord
  include ActionView::Helpers::TextHelper

  QUOTA_SIZES = [["1,0 GB",    1000000000],
                 ["2,0 GB",    2000000000], 
                 ["3,0 GB",    3000000000], 
                 ["5,0 GB",    5000000000], 
                 ["10,0 GB",  10000000000], 
                 ["20,0 GB",  20000000000], 
                 ["30,0 GB",  30000000000], 
                 ["50,0 GB",  50000000000], 
                 ["100,0 GB",100000000000]]

  delegate :url_helpers, to: 'Rails.application.routes'


  # relations
  belongs_to :author, class_name: "User"

  has_many :archivizations, dependent: :destroy
  has_many :accesses_groups, through: :archivizations, source: :group
  has_many :accesses_users, through: :archivizations, source: :users

  has_many :components, as: :componentable, dependent: :destroy
  has_many :works, as: :trackable
 
  # validates
  validates :name, presence: true,
                    length: { in: 1..75 },
                    uniqueness: { case_sensitive: false }

  validates :note, length: { in: 0..500 }

  validate :expiry_on_after_today
  validates :expiry_on, presence: true

  validates :archivizations, presence: true
  validate :only_quota_resize_up, unless: -> { (new_record? == true) }

  # callbacks

  # additionals
  accepts_nested_attributes_for :archivizations, reject_if: :all_blank, allow_destroy: true


  def self.for_user_in_archivizations(u)
    eager_load(archivizations: [group: :users])
      .where( archivizations: {groups: {members: {user_id: [u]} } } )  
  end

  def log_work(action = '', action_user_id = nil)
    worker_id = action_user_id || self.author_id
    url = "<a href=#{url_helpers.archive_path(self.id, locale: :pl)}>#{self.fullname}</a>".html_safe

    Work.create!(trackable_type: 'Archive', trackable_id: self.id, action: "#{action}", author_id: worker_id, url: "#{url}", 
      parameters: self.to_json(except: [:author_id], include: {archivizations: {only: [:id], include: { group: {only: [:id, :name]}, 
                                                                                                      archivization_type: {only: [:id, :name]}} }, 
                  author: {only: [:id, :user_name, :email]}}
      )
    )
  end


  def log_work_send_email(action = '', action_user_id = nil, recipients = nil)
    worker_id = action_user_id || self.author_id

    # puts recipients.class         #Mail::AddressContainer
    # puts recipients.first         #jan.kowalski@email.com
    # puts recipients.first.class   #String

    recipient = User.find_by(email: recipients.first)
    recipient_str = recipient.to_json(only: [:id, :user_name, :first_name, :last_name, :email], include: {author: {only: [:id, :user_name, :email]}}, root: 'recipient')
    recipient_hash = JSON.parse(recipient_str)
 
    archive_str = self.to_json( except: [:author_id], include: {author: {only: [:id, :user_name, :email]} }, root: 'archive' )
    archive_hash = JSON.parse(archive_str)

    # save for Archive Object
    archive_with_recipient_hash = archive_hash.merge(recipient_hash)
    archive_with_recipient_json = archive_with_recipient_hash.to_json 

    # url_archive = eval( "url_helpers.link_to( #{self.fullname}, archive_path(#{self.id}, locale: :pl), remote: false)")
    url_archive = "<a href=#{url_helpers.archive_path(self.id, locale: :pl)}>#{self.fullname}</a>".html_safe
    Work.create!(trackable_type: 'Archive', trackable_id: self.id, action: "#{action}", author_id: worker_id, url: "#{url_archive}", parameters: archive_with_recipient_json)

    # save for User Object
    recipient_with_archive_hash = recipient_hash.merge(archive_hash)
    recipient_with_archive_json = recipient_with_archive_hash.to_json 

    # url_user = eval( "url_helpers.link_to( #{self.fullname}, user_path(#{recipient.id}, locale: :pl), remote: false)")
    url_user = "<a href=#{url_helpers.user_path(recipient.id, locale: :pl)}>#{recipient.fullname}</a>".html_safe
    Work.create!(trackable_type: 'User', trackable_id: recipient.id, action: "#{action}", author_id: worker_id, url: "#{url_user}", parameters: recipient_with_archive_json)

  end


  def fullname
    "#{name}"
  end

  def fullname_was
    "#{name_was}"
  end

  def note_truncate
    truncate(Loofah.fragment(self.note).text, length: 250)
  end


  def is_expired?
    today = Time.zone.today
    if expiry_on >= today
      false
    else
      true
    end  
  end

  private
  
    def expiry_on_after_today
      return if expiry_on.blank?
     
      if is_expired?
        errors.add(:expiry_on, I18n.t('errors.messages.greater_than_or_equal_to', count: Time.zone.today.strftime('%Y-%m-%d')  ) ) 
        throw :abort 
      end 
    end

    def only_quota_resize_up
      if quota < quota_was
        errors.add(:quota, I18n.t('errors.messages.greater_than_or_equal_to', count: MyHuman.new.filesize(quota_was) )) 
        throw :abort 
      end 
    end

end

app/controllers/archives/components_controller.rb
class Archives::ComponentsController < ComponentsController
  before_action :set_componentable

  private

    def set_componentable
      @componentable = Archive.find(params[:archive_id])
    end

end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized, except: [:index, :datatables_index, :datatables_index_group, :datatables_index_user, :help_new_edit]
  before_action :set_archive, only: [:show, :edit, :update, :destroy, :send_link_to_archive_show]


  def datatables_index_group
    checked_filter = (params[:checked_only_filter].blank? || params[:checked_only_filter] == 'false' ) ? nil : true
    respond_to do |format|
      format.json { render json: GroupArchivesDatatable.new(params, view_context: view_context, only_for_current_group_id: params[:group_id], checked_only_filter: checked_filter) }
    end
  end

  def datatables_index_user
    checked_filter = (params[:checked_only_filter].blank? || params[:checked_only_filter] == 'false' ) ? nil : true
    respond_to do |format|
      format.json { render json: UserArchivesDatatable.new(params, view_context: view_context, only_for_current_user_id: params[:user_id], checked_only_filter: checked_filter) }
    end
  end

  def datatables_index
    # always set user_filter if current_user not have role archive:index
    if policy(:archive).index_in_role? 
      user_filter = (params[:eager_filter_for_current_user].blank? || params[:eager_filter_for_current_user] == 'false' ) ? nil : current_user.id
    else
      user_filter = current_user.id
    end

    respond_to do |format|
      format.json { render json: ArchiveDatatable.new(params, view_context: view_context, eager_filter: user_filter ) }
    end
  end

  def index
    authorize :archive, :index?
    respond_to do |format|
      # disable button all/my if current_user not have role archive:index
      format.html { render :index, locals: {index_in_role: policy(:archive).index_in_role?} }
    end
  end

  def show
    unless @archive.present?
      flash[:error] = t('errors.messages.not_found_resource')
      skip_authorization
      redirect_to root_path()
    else
      authorize @archive, :show?
      respond_to do |format|
        format.html { render :show }
      end
    end
  end

  # GET /archives/new
  def new
    @archive = Archive.new
    @archive.author = current_user
    @archive.quota = Rails.application.secrets[:archive_default_quota]
    @archive.expiry_on = Time.zone.today + Rails.application.secrets.archive_default_days_expiry_on_create.days
    authorize @archive, :new?
  end

  def help_new_edit
  end

  # GET /archives/1/edit
  def edit
    authorize @archive, :edit?
  end

  # POST /archives
  # POST /archives.json
  def create
    @archive = Archive.new(archive_params_create)
    @archive.author = current_user
    authorize @archive, :create?
    respond_to do |format|
      if @archive.save
        @archive.log_work('create', current_user.id)
        format.html { 
          flash[:success] = t('activerecord.successfull.messages.created', data: @archive.fullname)
          redirect_to archive_path(@archive.id) 
        }
        format.json { render :show, status: :created, location: @archive }
      else
        format.html { render :new }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archives/1
  # PATCH/PUT /archives/1.json
  def update
    @archive.author = current_user
    authorize @archive, :update?
    respond_to do |format|
      if @archive.update(archive_params)
        @archive.log_work('update', current_user.id)
        format.html { 
          flash[:success] = t('activerecord.successfull.messages.updated', data: @archive.fullname)
          redirect_to archive_path(@archive.id) 
        }
        format.json { render :show, status: :ok, location: @archive }
      else
        format.html { render :edit }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archives/1
  # DELETE /archives/1.json
  def destroy
    authorize @archive, :destroy?
    destroyed_clone = @archive.clone
    if @archive.destroy
      destroyed_clone.log_work('destroy', current_user.id)
      flash[:success] = t('activerecord.successfull.messages.destroyed', data: @archive.fullname)
      redirect_to archives_url
    else 
      flash.now[:error] = t('activerecord.errors.messages.destroyed', data: @archive.fullname)
      render :show
    end      
  end

  def send_link_to_archive_show
    authorize @archive, :send_link_to_archive_show?

    if params[:users_ids].blank?
      respond_to do |format|
        format.js { render :blank_users_ids }
      end
    else
      params[:users_ids].each do |i|
        user = User.find(i)
        CloudMailer.link_archive_show(@archive, user, current_user).deliver_later
      end
      respond_to do |format|
        format.js
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archive
      @archive = Archive.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def archive_params
      # params.require(:archive).permit(:name, :note)
      params.require(:archive).permit(policy(@archive).permitted_attributes)      
      # params.require(:archive).permit(:name, :note, archivizations_attributes: [:id, :archives_id, :group_id, :archivization_type_id, :_destroy])
    end

    def archive_params_create
      # params.require(:archive).permit(:name, :note)
      params.require(:archive).permit(policy(:archive).permitted_attributes)      
      # params.require(:archive).permit(:name, :note, archivizations_attributes: [:id, :archives_id, :group_id, :archivization_type_id, :_destroy])
    end

end

app/helpers/archives_helper.rb
require 'my_human'

module ArchivesHelper

  ICON = "archive"

  def archive_icon_legend
    fa_icon(ICON)
  end

  def archive_legend
    fa_icon(ICON, text: t("archives.show.title"))
  end

  def archive_show_legend
    fa_icon(ICON, text: t("archives.show.title"))
  end

  def archive_index_legend
    fa_icon(ICON, text: t("archives.index.title"))
  end

  def archive_edit_legend(data_obj=nil)
    data_obj.present? ? fa_icon(ICON, text: t("archives.edit.title") + ": " + data_obj.fullname_was) : fa_icon(ICON, text: t("helpers.links.edit") )
  end

  def archive_new_legend(data_obj=nil)
    data_obj.present? ? fa_icon(ICON, text: t("archives.new.title") + ": " + data_obj.fullname) : fa_icon(ICON, text: t("helpers.links.new") )
  end

  def archive_info_legend(data_obj)
    archive_show_legend + ": " + data_obj.fullname
  end

  def archive_human_size(data_size)
    MyHuman.new.filesize(data_size)
  end

end

app/views/archives/_data.html.erb
<div id="tab_data">
  <fieldset class="my-fieldset">
    <legend class="my-fieldset colored-title"><%= subtitle %></legend>
    <div class="row">

      <div class="col-sm-12">

        <%= form_errors_for @archive %>

        <div class="row">
          <div class="col-sm-6">
            <div class="row">

              <div class="form-group col-sm-12">
                <p><strong><%= Archive.human_attribute_name(:name) %></strong></p>
                <%= @archive.name %>
              </div>

              <div class="form-group col-sm-5">
                <p><strong><%= Archive.human_attribute_name(:expiry_on) %></strong></p>
                <%= @archive.expiry_on.present? ? @archive.expiry_on.strftime("%Y-%m-%d") : '' %>
              </div>

              <div class="form-group col-sm-7">
                <p><strong><%= Archive.human_attribute_name(:quota) %></strong></p>
                <%= archive_human_size(@archive.quota) %>
<!--            <%#= number_to_human_size(@archive.quota) %> -->
              </div>

            </div>  <!-- /row -->
          </div>  <!-- /col-sm-6 -->

          <div class="col-sm-6">
            <div class="row">

              <div class="form-group col-sm-12">
                <% if @archive.note.html_safe.size > 0 %>
                  <blockquote>
                    <%= @archive.note.html_safe %>
                  </blockquote>
                <% end %>
              </div>

            </div>  <!-- /row -->
          </div>  <!-- /col-sm-6 -->
        </div>  <!-- /row -->

        <div class="row">
          <div class="col-sm-12">

            <fieldset class="my-fieldset-short">
              <legend class="my-fieldset"><%= t('archives.fieldset.archivizations_title') %></legend>

              <table class="table table-hover">

                <thead>
                  <tr>
                    <th><%= Archivization.human_attribute_name(:group) %></th>
                    <th><%= Archivization.human_attribute_name(:archivization_type) %></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% @archive.archivizations.includes(:group).order('groups.name').each do |archivization| %>
                    <tr>
                      <td class="col-sm-5">
                        <%= link_to( archivization.group.fullname, group_path(archivization.group.id, archive_id: @archive.id), remote: true ) %>
                      </td>
                      <td class="col-sm-5"><%= archivization.archivization_type.try(:name) %></td>
                      <td class="col-sm-2"></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>

            </fieldset>

          </div>
        </div>  <!-- /row -->


        <hr class="hr-without-top-margin">

        <div class="row">
          <div class="col-sm-12">
<!-- 
            <%#= link_to archives_path, class: "btn btn-default" do %>
              <span class="fa fa-list"></span>
              <%#= t("helpers.links.index") %>
            <%# end %>
-->

            <% if policy(@archive).destroy? %>
              <%= link_to archive_path(@archive),
                                  method: :delete,
                                  data: { confirm: t('helpers.links.confirm_destroy', data: @archive.name) }, 
                                  class: "btn btn-danger" do %>
                <span class="fa fa-trash"></span>
                <%= t("helpers.links.destroy") %>
              <% end %>
            <% end %>

            <% if policy(@archive).edit? %>
              <%= link_to edit_archive_path(@archive), class: "btn btn-primary" do %>
                <span class="fa fa-edit"></span>
                <%= t("helpers.links.edit") %>
              <% end %>
            <% end %>

            <h6 class="pull-right"><%= last_updated_legend(@archive) %></h6>

          </div> <!--/col-sm-12 -->
        </div> <!-- /row -->

      </div> <!--/col-sm-12-->  

    </div>
  </fieldset>

</div>

app/views/archives/_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <%= form_with(model: archive, local: true) do |f| %>

      <% input_disabled ||= false  
         #if input_disabled is not passed to the partial it doesn't crash. 
         # We default it to false 
      %>

      <%= form_errors_for archive %>

      <div class="row">
        <div class="col-sm-6">
          <div class="row">

            <div class="form-group required col-sm-12">
              <%= f.label :name, class: 'control-label' %>
              <%= f.text_field :name, autofocus: true, class: 'form-control input-sm', disabled: input_disabled %>
            </div>

            <div class="form-group required col-sm-5">
              <%= f.label :expiry_on, class: 'control-label' %>
              <%= f.text_field :expiry_on, class: 'form-control input-sm datepicker', 
                                disabled: input_disabled %>
            </div>

            <div class="form-group col-sm-7">
              <%= f.label :quota, class: 'control-label' %>
              <%= f.select :quota, 
                    options_for_select(Archive::QUOTA_SIZES, selected: archive.quota), 
                    { include_blank: false}, 
                    { autofocus: false, class: 'form-control input-sm', 
                      disabled: false } %>
            </div>

          </div>  <!-- /row -->
        </div>  <!-- /col-sm-6 -->

        <div class="col-sm-6">
          <div class="row">

            <div class="form-group col-sm-12">
              <%= f.label :note, class: 'control-label' %>
              <%= f.trix_editor :note %>
              <%#= f.text_area :note, :rows => 4, class: 'form-control input-sm' %>
            </div>

          </div>  <!-- /row -->
        </div>  <!-- /col-sm-6 -->
      </div>  <!-- /row -->

      <% if policy(archive).add_remove_archive_group? %>

        <div class="row">
          <div class="col-sm-12">

            <fieldset class="my-fieldset">
              <legend class="my-fieldset"><%= t('archives.fieldset.archivizations_title') %></legend>

              <div class='archivizations clearfix'>

                <div class="row">
                  <div class="form-group required col-sm-5">
                    <%= f.label Archivization.human_attribute_name(:group_id), class: 'control-label' %>
                  </div>
                  <div class="form-group required col-sm-5">
                    <%= f.label Archivization.human_attribute_name(:archivization_type_id), class: 'control-label' %>
                  </div>
                </div>  <!-- /row -->

                <div class='archivizations-sub-form'>
                  <%= f.fields_for :archivizations, archive.archivizations.joins(:group).order('groups.name').reload do |archivization_form|  %>
                    <%= render 'archivization_fields', f: archivization_form %> 
                  <% end %>
                </div>
                <%= link_to_add_fields( t("helpers.links.link_to_add_fields_nested"), f, :archivizations) %>

              </div>

            </fieldset>

          </div> <!--/col-sm-12 -->
        </div>  <!-- /row -->

      <% end %>


      <hr class="hr-without-top-margin">

      <div class="row">
        <div class="col-sm-12">

          <%= link_to archive.new_record? ? archives_path() : archive_path(archive.id), class: "btn btn-default" do %>
            <%= back_from_new_or_edit_legend %>
          <% end %>
          
          <%= f.submit nil, class: 'btn btn-success' %>

        </div> <!--/col-sm-12 -->
      </div> <!-- /row -->
      
    <% end %>

  </div> <!--/col-sm-12-->
</div>


<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content"></div>
  </div>
</div>

app/views/archives/_help_new_edit_js.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h4 id="myModalLabel"><strong><%= help_legend %></strong></h4>
</div>
<div class="modal-body">

  <div class="row">

    <div class="form-group col-sm-12">
      <%= render 'help_new_edit_js_sub' %>
    </div>  <!-- /form-group col-sm-12 -->

  </div>  <!-- /row -->

</div>
<div class="modal-footer">
  <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true"><%= t('helpers.links.close') %></button>
</div>

app/views/archives/_help_new_edit_js_sub.en.html.erb
<div>
  <h4>/views/archives/help_new_edit_js_sub.en.html.erb</h4>
  <h3>EN</h3>
</div>

app/views/archives/_sidebar_edit.html.erb
<button class="sideber-button fa fa-chevron-right" onclick="changeSidebar(this)" title="<%=t('sidebar')%>" rel='tooltip'></button>

<div class="sidebar-content-small container-fluid">
  <div class="center"><%= archive_icon_legend %></div>
  <hr>

  <div class="row">
    <div class="col-sm-12">

      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">

        <li role="presentation" class="brand-nav"><%= link_to archives_path, title: t('.index'), rel: 'tooltip' do %>
          <span class="fa fa-list"></span>
          <% end %>
        </li>

        <li role="presentation" class="brand-nav"><%= link_to help_new_edit_archives_path, remote: true, title: t('.help'), rel: 'tooltip' do %>
            <span class="fa fa-info-circle"></span>
          <% end %>
        </li>

      </ul>

    </div>
  </div>

</div>    


<div class="sidebar-content-large hidden container-fluid">
  <div class="center"><%= archive_legend %></div>
  <hr>
  <div class="row">
    <div class="col-sm-12">


      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">
 
        <li role="presentation" class="brand-nav"><%= link_to archives_path, title: t('.index'), rel: 'tooltip' do %>
            <%= back_to_index_legend %>
          <% end %>
        </li>

        <li role="presentation" class="brand-nav"><%= link_to help_new_edit_archives_path, remote: true, title: t('.help'), rel: 'tooltip' do %>
          <%= help_legend %>
          <% end %>
        </li>

      </ul>


    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-sm-12">
      <div class="center"><%= fa_icon("edit", size: '2x') %></div>
      <h3 class="center"><%= t('helpers.links.edit') %></h3>
    </div>
  </div>


</div>

app/views/archives/_sidebar_index.html.erb
<button class="sideber-button fa fa-chevron-right" onclick="changeSidebar(this)" title="<%=t('sidebar')%>" rel='tooltip'></button>

<div class="sidebar-content-small container-fluid">
  <div class="center"><%= archive_icon_legend %></div>
  <hr>
   
  <div class="row">
    <div class="col-sm-12">

      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">

        <% if policy(:archive).new? %>
          <li role="presentation" class="brand-nav"><%= link_to new_archive_path, title: t('.new'), rel: 'tooltip' do %>
              <span class="fa fa-plus"></span>
            <% end %>
          </li>
        <% end %>

      </ul>

    </div>
  </div>

</div>    


<div class="sidebar-content-large hidden container-fluid">
  <div class="center"><%= archive_index_legend %></div>
  <hr>
  <div class="row">
    <div class="col-sm-12">

      <% if policy(:archive).new? %>
        <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">
   
          <li role="presentation" class="brand-nav"><%= link_to new_archive_path, title: t('.new'), rel: 'tooltip' do %>
            <span class="fa fa-plus"></span>
            <%= t('helpers.links.new') %>
            <% end %>
          </li>

        </ul>

      <% end %>

    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-sm-12">
      <div class="center"><%= fa_icon("list", size: '2x') %></div>
      <h3 class="center"><%= t('helpers.links.index') %></h3>
    </div>
  </div>

</div>

app/views/archives/blank_users_ids.js.erb
//toastr['info']("<%= t('success.messages.email_has_been_sent') %>");
toastr['error']("lista jest pusta");

app/views/archives/edit.html.erb
<div class="grid-container">

  <div class="sidebar">
    <%= render 'sidebar_edit' %>
  </div>

  <div class="main-content">
    <br>
    <div class="container-fluid"> 
      <div class="row">
        <div class="col-sm-12">
          <fieldset class="my-fieldset">
            <legend class="my-fieldset colored-title"><%= archive_edit_legend(@archive) %></legend>
            <%= render 'form', archive: @archive %>
          </fieldset>
        </div>

      </div>

    </div> <!--/container-fluid--> 
  </div> <!--/main-content--> 

</div> <!--/grid-containe--> 

app/views/archives/index.html.erb
<div class="grid-container">

  <div class="sidebar">
    <%= render 'sidebar_index' %>
  </div>

  <div class="main-content">
    <div class="container-fluid">

      <div class="row">
        <div class="col-sm-12">
          <h3 class="center colored-title index-title"><%= archive_index_legend %></h3>
        </div> <!--/col-sm-12 -->
      </div> <!--/row -->

      <div class="row">
        <div class="col-sm-12">
          <table id="archives-table" class="hover cell-border" cellspacing="0" width="100%" 
            data-source="<%= datatables_index_archives_path(format: :json) %>"
            data-locale_url="<%= datatables_lang_path(format: :json) %>"
            data-index_in_role="<%= index_in_role %>">
            <thead>
              <tr>
                <th>ID</th>
                <th><%= Archive.human_attribute_name(:name) %></th>
                <th><%= Archive.human_attribute_name(:note) %></th>
                <th><%= Archive.human_attribute_name(:expiry_on) %></th>
                <th><%= Archive.human_attribute_name(:folders_count) %></th>
                <th><%= Archive.human_attribute_name(:files_count) %></th>
                <th class="col-sm-2"><%= Archive.human_attribute_name(:files_size_sum) %></th>
            <!--<th><%#= Archive.human_attribute_name(:author) %></th> -->
              </tr>
            </thead>

            <tbody>
               <!--data from JSON -->
            </tbody>
          </table>
        </div> <!--/col-sm-12 -->
      </div> <!--/row -->

    </div> <!--/container-fluid--> 
  </div> <!--/main-content--> 

</div> <!--/grid-containe--> 